version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Check branch with docs source
  - package-ecosystem: "pip"
    target-branch: 'docs_source'
    directory: "/"
    schedule:
      interval: "daily"
