name: Build Documentation

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'serialix/**'


jobs:
  docs_build:
    runs-on: 'ubuntu-18.04'
    continue-on-error: false
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare docs git repository
        run: |
          git clone --single-branch --branch docs https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git temp_repo
          cd temp_repo
          rm -rf docs
          git config user.name 'Github Actions'
          git config user.email 'action@github.com'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and project
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Build documentation
        run: |
          make docs
          mv docs/_build/html ./temp_repo/docs


      - name: Push changes to remote
        run: |
          cd temp_repo
          git add --all
          git commit -m"Documentation build"
          git push
