name: Unit Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'examples/**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, windows-latest] <- append on release
        python-version: [3.5] # [3.6, 3.7, 3.8, 3.9] <- append on release

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and project
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest -v
