name: Publish to PyPi

on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-18.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies and project
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest -v

      - name: Build project
        run: make build

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PUBLISH_REPO_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PUBLISH_REPO_PASSWD }}
        run: make publish
