name: Publish to PyPi

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies and project
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Build project
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPi
        env:
          TWINE_REPOSITORY_URL: ${{ secrets.PUBLISH_REPO_URL }}
          TWINE_USERNAME: ${{ secrets.PUBLISH_REPO_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PUBLISH_REPO_PASSWD }}
        run: twine upload dist/*
